version: '2'

services:
  db:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    networks:
      - 'app-tier'  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 50s
      retries: 5
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/bitnami/redis/data'
    networks:
      - 'app-tier'  
  gateway:
    build: ./gateway/.  
    networks:
      - 'app-tier'  
    environment:
      - 'PORT=5000'
      - 'NOTIFICATION_PORT=5001'
      - 'NOTIFICATION=notification'
    ports:
      - "5000:5000"

  notification:
    build: ./notification-processor/.  
    networks:
      - 'app-tier'  
    environment:
      - 'instance=1'
      - 'PORT=5001'
      - 'POSTGRES_HOST=db'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
  authorizator:
    build: ./authorizator/.  
    networks:
      - 'app-tier'  
    environment:
      - 'PORT=5002'
      - 'POSTGRES_HOST=db'
      - 'POSTGRES_PORT=5432'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy        
volumes:
  postgresql_data:
    driver: local
networks:
  app-tier:
    name: app-tier
    driver: bridge

    